Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Flowpack.NodeVariantSelector:
            - Main
    Ui:
      resources:
        javascript:
          'Flowpack.NodeVariantSelector:NodeVariantSelector':
            resource: resource://Flowpack.NodeVariantSelector/Public/JavaScript/NodeVariantSelector/Plugin.js